services:
  db:
    image: postgres:16
    container_name: desafio2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: teste
    ports:
      - "5432:5432"
    volumes:
      - volume_desafio2:/var/lib/postgresql/data

volumes:
  volume_desafio2:
